const path = require( 'path' )
const writeFile = require( '../fs-helper/writeFile' )
const { site } = require( '../project-path' ) ,
    routeFilePath = path.resolve( site , 'router/componentRoutes.js' )

const tempG = ( objStr = '[]' ) => (
`/* Do not modify, automatically generated by the script program */

export const componentRoutes = ${ objStr } `
)

exports.writeRouteConfig = function( configs = [] ){
    let routes = configs.map( item => {
        let { name , readMeConfig } = item ,
            route = { path: name }
        if ( readMeConfig ) {
            let { title } = readMeConfig
            Object.assign( route , {
                meta: {
                    name: title ,
                }
            } )
        }
        return route
    } )
    let strRoutes = JSON.stringify( routes , null , 4 )
        tmp = tempG( strRoutes )
    writeFile( routeFilePath , tmp ).catch( console.warn )
}